name: on-push

on: push

jobs:
  test-on-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "executed"

      - name: debug
        shell: bash
        run: |
          set -xe

          echo github context '${{ github }}'
          env

      - uses: jksy/checkout-with-reference@v0.4
        with:
          github_token: ${{ github.token }}
          github_actor: ${{ github.actor }}
          github_repository: ${{ github.repository }}
          reference_dir: /not-exists
          checkout_dir: .
